# -----------------------------
# REQUIRED SITE CONFIGURATION
# -----------------------------
# Explicitly set the encoding to use UTF-8 regardless of the server's default
encoding: "utf-8"

# Set the base hostname & protocol for your site
url: "https://akingdom.github.io" 
baseurl: "" # This should be empty for a User/Organization Page like yours

# Add files and directories to the global exclude list 
# so Jekyll ignores them during the build process entirely.
exclude:
  - googlea1314b9930e3daf4.html
  - images/posts/
  
# -----------------------------
# PLUGINS
# -----------------------------
# The jekyll-sitemap plugin is built-in to GitHub Pages and must be listed here to run
plugins:
  - jekyll-sitemap
